# Exploratory Data Analysis 


Understanding the dataset to explore how the dataset is presentin the database and if there is a need of creating aggregated tables that can help with:

1) Vendor selection for profitability
2) Product pricing optimization

In [1]:
import pandas as pd
import sqlite3

In [2]:
#creating database connection
conn = sqlite3.connect('inventory.db')

In [3]:
tables = pd.read_sql_query("select name from sqlite_master where type ='table'", conn)
tables

                         name
0  begin_inventory-checkpoint
1             begin_inventory
2               end_inventory
3                   purchases
4             purchase_prices
5                       sales
6              vendor_invoice
7        vendor_sales_summary

In [4]:
for table in tables['name']:
    print('-'*50, f'{table}','-'*50)
    print('Count of records : ',pd.read_sql(f'select count(*) as count from "{table}"', conn)['count'].values[0])
    display(pd.read_sql(f'select * from "{table}" limit 5',conn))

-------------------------------------------------- begin_inventory-checkpoint --------------------------------------------------
Count of records :  206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records :  206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records :  224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records :  2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records :  12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records :  12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records :  5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records :  10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750.0,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750.0,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750.0,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750.0,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750.0,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07

In [5]:
purchases = pd.read_sql_query('select * from purchases where VendorNumber = 4466 ', conn)
purchases.shape

(2192, 16)

In [6]:
purchase_prices = pd.read_sql_query('select * from purchase_prices where VendorNumber = 4466', conn)
purchase_prices.shape

(3, 9)

In [7]:
vendor_invoice = pd.read_sql_query('select * from vendor_invoice where VendorNumber = 4466', conn)
vendor_invoice.shape

(55, 10)

In [8]:
sales = pd.read_sql_query('select * from sales where VendorNo = 4466', conn)
sales.shape

(9453, 14)

In [9]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [10]:
sales.groupby(['Brand'])[['SalesQuantity','SalesPrice','SalesDollars']].sum()

       SalesQuantity  SalesPrice  SalesDollars
Brand
3140            3890    30071.85      50531.10
5215            4651    41542.02      60416.49
5255            6096    51180.60      79187.04

- The purchases table contains actual purchase data, including the data of purchase, products(brands) purchased by vendors, the amount paid and the quantity purchased
- The purchase price column is derived from the purchase_price table, whice provides product-wise actual and purchase prices. The combination of vendor and brand is unique in this table. 
- The vendor_invoice table aggregates data fromthe purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. Thsi table maintains uniqueness based on vendor and PO number.
- The sales table captures actual sales transaction, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

- purchasing transactions made by vendors
- sales transaction data
- freight costs for each vendor
- actual product prices from vendors

In [11]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [12]:
freight_summary = pd.read_sql_query(""" select VendorNumber, sum(Freight) as FreightCost
from vendor_invoice 
group by VendorNumber""", conn)

In [13]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [14]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [15]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [16]:
pd.read_sql_query(""" select 
p.VendorNumber,
p.VendorName,
p.Brand,
p.PurchasePrice,
sum(p.Quantity) as TotalPurchaseQuantity,
sum(p.Dollars) as TotalPurchaseDollars,
pp.Volume,
pp.Price as ActualPrice
from purchases p
join purchase_prices pp
on p.Brand = pp.Brand 
where pp.PurchasePrice>0
group by p.VendorNumber,p.VendorName,p.Brand
order by TotalPurchaseDollars

""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice
0,7245,PROXIMO SPIRITS INC.,3065,0.71,1,0.71,50,0.99
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,1,1.47,200,1.99
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,2,1.48,50,0.99
3,8004,SAZERAC CO INC,5683,0.39,6,2.34,50,0.49
4,9815,WINE GROUP INC,8527,1.32,2,2.64,750,4.99
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,138109,3023206.01,1750,29.99
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,201682,3261197.94,1750,22.99
10689,17035,PERNOD RICARD USA,8068,18.24,187407,3418303.68,1750,24.99
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,164038,3804041.22,1750,28.99
10691,1128,BROWN-FORMAN CORP,1233,26.27,145080,3811251.60,1750,36.99

In [17]:
# SALES TRANSACTION DATA

sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [18]:
pd.read_sql_query(""" select 
   VendorNo,
   Brand,
   SUM(SalesDollars) AS TotalSalesDollars,
   SUM(SalesPrice) AS TotalSalesPrice,
   SUM(SalesQuantity) AS TotalSalesQuantity,
   SUM(ExciseTax) AS TotalExciseTax
   from sales
   group by VendorNo, Brand
   order by TotalSalesDollars
   """, conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,9.800000e-01,0.98,2,0.10
1,9206,2773,9.900000e-01,0.99,1,0.05
2,3252,3933,1.980000e+00,0.99,2,0.10
3,3924,9123,1.980000e+00,0.99,2,0.10
4,10050,3623,1.980000e+00,1.98,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4.223108e+06,545778.28,135838,249587.83
11268,3960,4261,4.475973e+06,420050.01,200412,368242.80
11269,17035,8068,4.538121e+06,461140.15,187140,343854.07
11270,4425,3405,4.819073e+06,561512.37,160247,294438.66
11271,1128,1233,5.101920e+06,672819.31,142049,260999.20

In [19]:
vendor_sales_summary = pd.read_sql_query(""" WITH FreightSummary AS 
(select VendorNumber, sum(Freight) as FreightCost
from vendor_invoice 
group by VendorNumber),

PurchaseSummary AS ( select 
p.VendorNumber,
p.VendorName,
p.Brand,
p.Description,
p.PurchasePrice,
sum(p.Quantity) as TotalPurchaseQuantity,
sum(p.Dollars) as TotalPurchaseDollars,
pp.Volume,
pp.Price as ActualPrice
from purchases p
join purchase_prices pp
on p.Brand = pp.Brand 
where pp.PurchasePrice>0
group by p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price,pp.Volume
),

SalesSummary AS ( select 
   VendorNo,
   Brand,
   SUM(SalesDollars) AS TotalSalesDollars,
   SUM(SalesPrice) AS TotalSalesPrice,
   SUM(SalesQuantity) AS TotalSalesQuantity,
   SUM(ExciseTax) AS TotalExciseTax
   from sales
   group by VendorNo, Brand
)

select 
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ps.Volume,
    ps.ActualPrice,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalSalesQuantity,
    ss.TotalExciseTax,
    fs.FreightCost
from PurchaseSummary ps
left join SalesSummary ss
on ps.VendorNumber = ss.VendorNo 
and ps.Brand = ss.Brand
left join FreightSummary fs
on ps.VendorNumber = fs.VendorNumber
order by ps.TotalPurchaseDollars desc
""",conn)

In [20]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,2,2.64,750,4.99,1.595000e+01,10.96,5.0,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,6,2.34,50,0.49,6.566000e+01,1.47,134.0,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,2,1.48,50,0.99,1.980000e+00,0.99,2.0,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1,1.47,200,1.99,1.432800e+02,77.61,72.0,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,1,0.71,50,0.99,8.514000e+01,33.66,86.0,4.46,38994.78

This query generates a vendor-wise and purchase summary, which is valuable for:
    
Performance Optimization:

        - The query involves heavy joins and aggregates on large datasets like sales and purchases.
        - Storing the pre-aggregated results avoids repeated expensive computations.
        - Helps in analysing sales, purchses and pricing for different vendors and brands.
        - Future benefit for storing this data is for faster dashboarding and reporting
        - Instead of running expensive query each time, dashboards can fetch data quickly from vendor_sales_summary

In [21]:
# Data cleaning

vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
Volume                    object
ActualPrice              float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [22]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
Volume                     0
ActualPrice                0
TotalSalesDollars        178
TotalSalesPrice          178
TotalSalesQuantity       178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [23]:
vendor_sales_summary['VendorName'].unique() # Has some spaces between

array(['BROWN-FORMAN CORP          ', 'MARTIGNETTI COMPANIES',
       'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
       'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
       'MOET HENNESSY USA INC      ', 'CAMPARI AMERICA            ',
       'SAZERAC CO INC             ', 'CONSTELLATION BRANDS INC   ',
       'M S WALKER INC             ', 'SAZERAC NORTH AMERICA INC. ',
       'PALM BAY INTERNATIONAL INC ', 'REMY COINTREAU USA INC     ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'WILLIAM GRANT & SONS INC   ', 'HEAVEN HILL DISTILLERIES   ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'STE MICHELLE WINE ESTATES  ', 'TRINCHERO FAMILY ESTATES   ',
       'MHW LTD                    ', 'WINE GROUP INC             ',
       'PERFECTA WINES             ', 'LUXCO INC                  ',
       'TREASURY WINE ESTATES      ', 'DIAGEO CHATEAU ESTATE WINES',
       'SHAW ROSS INT L IMP LTD    ', 'PINE STATE TRADING CO      ',
       'PHILLIPS PRODUCTS CO.      ', 'CALEDONIA SPIRITS INC      ',
       'STATE WINE & SPIRITS   ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'VINEYARD BRANDS INC        ',
       'DELICATO VINEYARDS INC     ', 'FABRIZIA SPIRITS LLC       ',
       'DUGGANS DISTILLED PRODUCTS ', 'Serralles Usa LLC          ',
       'SEA HAGG DISTILLERY LLC    ', 'OLE SMOKY DISTILLERY LLC   ',
       'VRANKEN AMERICA            ', 'KLIN SPIRITS LLC           ',
       'LAIRD & CO                 ', 'ADAMBA IMPORTS INTL INC    ',
       'LATITUDE BEVERAGE COMPANY  ', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'CHARLES JACQUIN ET CIE INC ',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY           ',
       'AMERICAN VINTAGE BEVERAGE  ', 'MANGO BOTTLING INC         ',
       'SWEET BABY VINEYARD        ', 'NICHE W & S                ',
       'LABELLE VYDS AND WINERY    ', 'FLAG HILL WINERY & VINEYARD',
       'SMOKY QUARTZ DISTILLERY LLC', 'PREMIUM PORT WINES, INC.   ',
       'Russian Standard Vodka     ', 'Dunn Wine Brokers          ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'VINILANDIA USA             ', 'PARK STREET IMPORTS LLC    ',
       'TAKARA SAKE USA INC        ', 'SEA BREEZE CELLARS LLC     ',
       'STARK BREWING COMPANY      ', 'TY KU LLC                  ',
       'PSP WINES ', 'TAMWORTH DISTILLING        ',
       'ZORVINO VINEYARDS          ', 'SOUTHERN GLAZERS W&S OF NE ',
       'HOOD RIVER DISTILLERS, Inc.', 'CRUSH WINES                ',
       'POVERTY LANE ORCHARDS      ', 'DJINN SPIRITS LLC          ',
       'MOONLIGHT MEADERY          ', 'TALL SHIP DISTILLERY LLC   ',
       'FORTUNE WINE BROKERS LLC   ', 'BLACK COVE BEVERAGES       ',
       'VINEXTRA INC               ', 'SURVILLE ENTERPRISES CORP  ',
       'JEWELL TOWNE VINEYARDS     ', 'SWEETWATER FARM         ',
       'MARTIGNETTI COMPANIES ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'INCREDIBREW INC            ',
       'ALISA CARR BEVERAGES           ', 'STELLAR IMPORTING CO LLC   ',
       'FULCHINO VINEYARD INC      ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'VINEDREA WINES LLC         ',
       'BLACK PRINCE DISTILLERY INC', 'VINEYARD BRANDS LLC        ',
       'THE IMPORTED GRAPE LLC     ', 'WALPOLE MTN VIEW WINERY    ',
       'GILMANTON WINERY & VINEYARD', 'HAUNTING WHISPER VYDS      ',
       'STAR INDUSTRIES INC.       ', 'LOYAL DOG WINERY           ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'APPOLO VINEYARDS LLC       ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE  ', 'UNCORKED       ',
       'BRONCO WINE COMPANY        ', 'MILTONS DISTRIBUTING CO    ',
       'TRUETT HURST               ', 'LAUREATE IMPORTS CO        ',
       'FANTASY FINE WINES CORP    ', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS     ', 'CAPSTONE INTERNATIONAL     ',
       'FLAVOR ESSENCE INC         '], dtype=object)

In [24]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype('float64')

In [25]:
vendor_sales_summary.fillna(0, inplace = True)

In [26]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip() #Now spaces removed

In [27]:
#vendor_sales_summary['VendorName'].unique()

In [28]:
vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [29]:
vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100

In [30]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [31]:
vendor_sales_summary['SalestoPurchaseratio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [32]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'TotalPurchaseQuantity', 'TotalPurchaseDollars', 'Volume',
       'ActualPrice', 'TotalSalesDollars', 'TotalSalesPrice',
       'TotalSalesQuantity', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalestoPurchaseratio'],
      dtype='object')

In [33]:
cursor = conn.cursor()

In [34]:
cursor.execute( """   create table if not exists vendor_sales_summary (
VendorNumber int,
VendorName varchar(100),
Brand int,
Description varchar(100),
PurchasePrice decimal(10,2),
ActualPrice decimal(10,2),
Volume,
TotalPurchaseQuantity int,
TotalPurchaseDollars decimal(15,2),
TotalSalesQuantity int,
TotalSalesDollars decimal(15,2),
TotalSalesPrice decimal(15,2),
TotalExciseTax decimal(15,2),
FreightCost decimal(15,2),
GrossProfit decimal(15,2),
ProfitMargin decimal(15,2),
StockTurnover decimal(15,2),
SalestoPurchaseratio decimal(15,2),

primary key (VendorNumber, Brand)
)
"""  )

In [35]:
pd.read_sql_query(" select * from vendor_sales_summary",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750.0,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750.0,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750.0,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750.0,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750.0,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,2,2.64,750.0,4.99,1.595000e+01,10.96,5.0,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,6,2.34,50.0,0.49,6.566000e+01,1.47,134.0,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,2,1.48,50.0,0.99,1.980000e+00,0.99,2.0,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1,1.47,200.0,1.99,1.432800e+02,77.61,72.0,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,1,0.71,50.0,0.99,8.514000e+01,33.66,86.0,4.46,38994.78

In [36]:
vendor_sales_summary.to_sql("vendor_sales_summary",conn, if_exists = 'replace', index = False)

10692

In [37]:
 # Final table

pd.read_sql_query(" select * from vendor_sales_summary",conn)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseratio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750.0,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68,1.290668e+06,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750.0,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24,1.015032e+06,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750.0,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22,1.119817e+06,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750.0,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07,1.214775e+06,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750.0,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07,1.199902e+06,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,2,2.64,750.0,4.99,1.595000e+01,10.96,5.0,0.55,27100.41,1.331000e+01,83.448276,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,6,2.34,50.0,0.49,6.566000e+01,1.47,134.0,7.04,50293.62,6.332000e+01,96.436186,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,2,1.48,50.0,0.99,1.980000e+00,0.99,2.0,0.10,14069.87,5.000000e-01,25.252525,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1,1.47,200.0,1.99,1.432800e+02,77.61,72.0,15.12,257032.07,1.418100e+02,98.974037,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,1,0.71,50.0,0.99,8.514000e+01,33.66,86.0,4.46,38994.78,8.443000e+01,99.166079,86.000000,119.915493

In [38]:

import sqlite3
import pandas as pd
import logging 
from ingestion_db import ingest_db

logging.basicConfig(
       filename = "logs/get_vendor_summary.log",
       level = logging.DEBUG,
       format = "%(asctime)s-%(levelname)s-%(message)s",
       filemode="a",
       force=True
)

def create_vendor_summary (conn):
    
    """ this function will merge the different tables to get the overall vendor summary and adding new column in the resultant data"""
    
    vendor_sales_summary = pd.read_sql_query(""" WITH FreightSummary AS 
    (select VendorNumber, sum(Freight) as FreightCost
    from vendor_invoice 
    group by VendorNumber),

    PurchaseSummary AS ( select 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    p.PurchasePrice,
    sum(p.Quantity) as TotalPurchaseQuantity,
    sum(p.Dollars) as TotalPurchaseDollars,
    pp.Volume,
    pp.Price as ActualPrice
    from purchases p
    join purchase_prices pp
    on p.Brand = pp.Brand 
    where pp.PurchasePrice>0
    group by p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price,pp.Volume
    ),

    SalesSummary AS ( select 
       VendorNo,
       Brand,
       SUM(SalesDollars) AS TotalSalesDollars,
       SUM(SalesPrice) AS TotalSalesPrice,
       SUM(SalesQuantity) AS TotalSalesQuantity,
       SUM(ExciseTax) AS TotalExciseTax
       from sales
       group by VendorNo, Brand
    )

    select 
        ps.VendorNumber,
        ps.VendorName,
        ps.Brand,
        ps.Description,
        ps.PurchasePrice,
        ps.TotalPurchaseQuantity,
        ps.TotalPurchaseDollars,
        ps.Volume,
        ps.ActualPrice,
        ss.TotalSalesDollars,
        ss.TotalSalesPrice,
        ss.TotalSalesQuantity,
        ss.TotalExciseTax,
        fs.FreightCost
    from PurchaseSummary ps
    left join SalesSummary ss
    on ps.VendorNumber = ss.VendorNo 
    and ps.Brand = ss.Brand
    left join FreightSummary fs
    on ps.VendorNumber = fs.VendorNumber
    order by ps.TotalPurchaseDollars desc
    """,conn)
    return vendor_sales_summary

def clean_data(df):
    
    # Changing data type to float
    df['Volume']=df['Volume'].astype('float64')
    
    # Filling missing values with 0
    df.fillna(0, inplace = True)
    
    # Removing spaces from categorical columns
    df['VendorName'] = df['VendorName'].str.strip()
    df['Description'] = df['Description'].str.strip()
    
    #creating new columns for better analysis
    vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']
    vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100
    vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']
    vendor_sales_summary['SalestoPurchaseratio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']
    
    return df


if __name__ == '__main__':
    
    # creating database connection
    
    conn = sqlite3.connect('inventory.db')
    
    logging.info('Creating Vendor Summary Table....')
    summary_df = create_vendor_summary(conn)
    logging.info(summary_df.head())
    
    logging.info('Cleaning Data....')
    clean_df = clean_data(summary_df)
    logging.info(clean_df.head())
    
    logging.info('Ingesting Data....')
    ingest_db(clean_df,'vendor_sales_summary',conn)
    logging.info('Completed')

In [39]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseratio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750.0,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68,1.290668e+06,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750.0,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24,1.015032e+06,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750.0,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22,1.119817e+06,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750.0,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07,1.214775e+06,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750.0,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07,1.199902e+06,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,2,2.64,750.0,4.99,1.595000e+01,10.96,5.0,0.55,27100.41,1.331000e+01,83.448276,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,6,2.34,50.0,0.49,6.566000e+01,1.47,134.0,7.04,50293.62,6.332000e+01,96.436186,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,2,1.48,50.0,0.99,1.980000e+00,0.99,2.0,0.10,14069.87,5.000000e-01,25.252525,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1,1.47,200.0,1.99,1.432800e+02,77.61,72.0,15.12,257032.07,1.418100e+02,98.974037,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,1,0.71,50.0,0.99,8.514000e+01,33.66,86.0,4.46,38994.78,8.443000e+01,99.166079,86.000000,119.915493

In [40]:
import numpy as np

vendor_sales_summary = vendor_sales_summary.replace(
    [np.inf, -np.inf],
    np.nan
)

In [41]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = 'root'
password = quote_plus('Chandru@2005')
host = '127.0.0.2'
port = '3306'
database = 'vendor_sales_db'

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "vendor_sales"
vendor_sales_summary.to_sql(table_name, engine, if_exists = "replace", index = False)

pd.read_sql("select * from vendor_sales limit 5;", engine)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseratio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,145080,3811251.60,1750.0,36.99,5.101920e+06,672819.31,142049.0,260999.20,68601.68,1.290668e+06,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,164038,3804041.22,1750.0,28.99,4.819073e+06,561512.37,160247.0,294438.66,144929.24,1.015032e+06,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,187407,3418303.68,1750.0,24.99,4.538121e+06,461140.15,187140.0,343854.07,123780.22,1.119817e+06,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,201682,3261197.94,1750.0,22.99,4.475973e+06,420050.01,200412.0,368242.80,257032.07,1.214775e+06,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,138109,3023206.01,1750.0,29.99,4.223108e+06,545778.28,135838.0,249587.83,257032.07,1.199902e+06,28.412764,0.983556,1.396897